QA/TSWEB/146-27-09-2022
VitaliiDolotov/ts_website_automation pull request #13
Opened 2022-09-27 15:45 UTC by vh-qa

New tests 

1. CheckNavigationHeaderOnJobPage
2. CheckLocalizationOnJobPage
3. CheckPaginationOnCareerPage

created

2022-10-05 15:54 UTC, VitaliiDolotov submitted a review, later dismissed

2022-10-31 14:44 UTC, DaniilVostrikov approved these changes

2022-11-01 10:12 UTC, UncleDanya approved these changes

2022-11-02 11:45 UTC, VitaliiDolotov requested changes

2022-11-02 11:45 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/ComponentSteps/PaginationComponentSteps.cs
> +        // position can only be "next" or "previous"
Start comment from capital letter.
If you really like to limit input use enum instead of comment

2022-11-02 11:45 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/ComponentSteps/PaginationComponentSteps.cs
> +        [When(@"User clicks on '(.*)' direction button in pagination panel")]
It is a good practice to not mix When and Then steps. So the structure of file should be the following
1. All Given steps
2. All When steps
3. All Then steps

2022-11-02 11:45 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/ComponentSteps/PaginationComponentSteps.cs
> +            var navigationButton = _page.Component<Pagination>().ArrowButtonByDirection(direction).ElementHandleAsync()
In the step definition you say that button should be Displayed but in the step you check only for exists state? Why to not check for Displayed?

2022-11-03 15:08 UTC, VitaliiDolotov requested changes

2022-11-03 15:08 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/ComponentSteps/PaginationComponentSteps.cs
> +            paginationButtons.Should().NotBeNull();
Same comment with displayed. Please check other places by yourself

2022-11-03 15:19 UTC, VitaliiDolotov approved these changes

2022-11-03 15:30 UTC, merged