Fix-tests-with-new-mastre
VitaliiDolotov/ts_website_automation pull request #29
Opened 2022-11-17 22:23 UTC by UncleDanya

2022-11-18 11:32 UTC, DaniilVostrikov requested changes

2022-11-18 11:32 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Steps/GeneralSteps.cs
> +        public void WhenUserExpectsObjectsToBeCreated(Table table)
update as expected

2022-12-01 14:35 UTC, DaniilVostrikov approved these changes

2022-12-05 13:35 UTC, VitaliiDolotov requested changes

2022-12-05 13:35 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Components/Pagination.cs
> +        public ILocator FirstPage => Instance.Locator("//div[text()='01']");
1. Please try to avoid using text in selectors.
2. Why we have only selector to the first page? How it will be possible to interact with other pages?

2022-12-05 13:35 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Extensions/LocatorExtensions.cs
> +        public static int Count(this ILocator locator)
LB before method

2022-12-05 13:35 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Extensions/StringExtensions.cs
> +            // replace white spaces with undescore, then replace all invalid chars with empty string
I suppose all comments should be started from capital latter

2022-12-05 13:35 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/GeneralSteps.cs
> +        [When(@"User expects objects to be created")]
This statement is very generic. Could you please add more context to the step definition?

2022-12-05 13:35 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/GeneralSteps.cs
> +                        _page.WaiterWithReloadPage(tagElement);
Wait can't be a replacement for assertion

2022-12-05 13:35 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/GeneralSteps.cs
> +                    case "Tag":
Do not use switch without default

2022-12-05 13:35 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +        public static void WaiterWithReloadPage(this IPage page, ILocator locator, string amountOfTime = "ExtraLong")
1. I would recommend to make this as page extension
2. Can we change amountOfTime type to enum?

2022-12-05 16:49 UTC, VitaliiDolotov requested changes

2022-12-05 16:49 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +                    page.ReloadAsync().GetAwaiter().GetResult();
Move these two lines below second if. In this case first if can be removed completely

2022-12-05 16:49 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +                throw new Exception("Timeout 120000ms exceeded.");
Create separate variable with seconds for wait. Then use it in wait statement and in the exception multiplying to attempts time

2022-12-05 16:49 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +        public static void WaitForDefaultCareers(this IPage page, List<string> careersList, string amountOfAttempt = "FiveAttempt")
If this method related to the Pagination page it must be on Pagination class

2022-12-05 16:49 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +                    goto restart;
Do **NOT** use goto

2022-12-05 16:49 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +        public enum AmountOfTime
What is the reason why we use enums instead of just passing numbers to methods?

2022-12-05 20:30 UTC, UncleDanya commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +        public static void WaitForDefaultCareers(this IPage page, List<string> careersList, string amountOfAttempt = "FiveAttempt")
This method is related to the Pagination page only when we wait for more than 10 default careers, if there are less than 10 we don't need pagination on the page

2022-12-05 20:34 UTC, UncleDanya commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +                    goto restart;
I don't know how it will be better. Because if I don't use goto, I'm going to use to while with one more foreach with try/catch block

2022-12-05 20:44 UTC, UncleDanya commented on ui_tests/PlaywrightAutomation/Utils/Waiters/CustomWaiter.cs
> +        public enum AmountOfTime
The reason is the same as in 'NumberOfAttempts'. We want to give a variants time for future use

2022-12-07 16:12 UTC, DaniilVostrikov requested changes

2022-12-07 16:12 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Pages/Career/CareerMainPage.cs
> +            if (pagination.IsVisibleAsync().Result)
What you think about creating method like "MoveToAndCheckPaginationArrow", that will check if pagination exists, then hover to it, and than check arrow button existing (return bool)? 
if will replace this 'if' and 57 line if it will be used on 55 line

2022-12-07 16:12 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Steps/GeneralSteps.cs
> +        [When(@"User waits careers with default descriptions and tags")]
let's change the definition from 'default' to another word describing this type of data

2022-12-07 16:40 UTC, DaniilVostrikov requested changes

2022-12-07 16:40 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Extensions/PageExtensions.cs
> +            var ms = 5000;
@VitaliiDolotov what do you think about this value? should we cover it to something?

2022-12-07 16:42 UTC, DaniilVostrikov submitted a review, later dismissed

2022-12-27 11:46 UTC, VitaliiDolotov requested changes

2022-12-27 11:46 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Components/Pagination.cs
> +        public bool MoveToAndCheckPaginationArrow()
Maybe rename to something line this FocusAndGetPaginationArrowDisplayedState?

2022-12-27 11:46 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Extensions/PageExtensions.cs
> +            var ms = 5000;
It looks fine for me

2023-01-03 13:51 UTC, DaniilVostrikov approved these changes

2023-01-03 13:54 UTC, VitaliiDolotov approved these changes

2023-01-03 16:45 UTC, merged